### ISSUE TITLE
Key points of milestone 1.0

### ISSUE THREAD

**Issue by eyworldwide** [galacean/galacean.github.io#544]
# User interface
- [x] Redesign homepage
- [x] Refactor the website with radix-ui
- [x] Add day/night theme
- [ ] Redesign the diagrams in doc with new tool

# Contents
- [x] Add docs of editor
- [x] Add an introduction of engine
- [ ] Playground contents
